Library
uryelah/-Microverse-601-Library pull request #1
Opened 2020-01-29 22:25 UTC by thsvr

2020-01-30 21:02 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome Design :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Below are part of the checklist for this project, kindly work on these few things listed below;**

**_1. Kindly attend to my comments below_**

**_2. A user shouldn't be able to add a book with empty value right._**
![image](https://user-images.githubusercontent.com/31897434/73489750-70d99e00-43ab-11ea-8f01-76c5a662e420.png)

**_3. Kindly update your `README` with a live link, `README` file without live link doesn't look professional._**
Example: https://raw.githack.com/uryelah/-Microverse-601-Library/library/index.html
Kindly watch this video tutorial on how to create live link below 👇;
[Video Tutorial](https://www.loom.com/share/76088842a2d14322bbcf65b884f4d42d)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/

**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-01-30 21:02 UTC, bellom commented on .eslintrc.json
> +    "ignorePatterns": ["*.json"],
You made some changes in this file, check out the [microverse-linter-config](https://github.com/microverseinc/linters-config/tree/master/javascript)
![image](https://user-images.githubusercontent.com/31897434/73417568-ca44bd00-4318-11ea-8a5e-fedabd629b8c.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/

2020-01-30 21:02 UTC, bellom commented on index.js
> +// get latested localStorage values
It’s better to delete commented code. If you need to review a previous version of your code, use git history, your code is clear enough to understand 🙂 ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

Kindly remove all commented code

2020-01-30 21:02 UTC, bellom commented on index.js
> +  <h3>${book.title}</h3>
Let separate the DOM from application logic, you can create another file for DOM.
![image](https://user-images.githubusercontent.com/31897434/73420341-70e18b80-4322-11ea-840a-fa14e04b592b.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59623451/

2020-01-30 21:02 UTC, bellom commented on index.js
> +  // update value of read as oposite of current value
It’s better to delete commented code. If you need to review a previous version of your code, use git history, your code is clear enough to understand 🙂 ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

Kindly remove all commented code

2020-01-30 21:54 UTC, uryelah commented on index.js
> +// get latested localStorage values
That's a comment describing the function bellow, we'll rewrite it to read better like a normal comment

2020-01-30 21:58 UTC, uryelah commented on index.js
> +  // update value of read as oposite of current value
That's a comment describing the function bellow, we'll rewrite it to read better like a normal comment

2020-01-30 23:42 UTC, uryelah commented
**Hey there!** 
We did the requested changes from the last review.
Can you take a look if it's enough for approval? 
We are open to feedback 🙂

**P.S.:**
We, as suggested by Bello, added `/* eslint-disable no-unused-vars, no-unused-vars */ comments to the functions being called inside <tag onclick='function'> and on the logic.js file due to eslint not being able to recognize that they were being used in the html and/or at the other script file.
`

2020-01-31 13:58 UTC, bolah2009 approved these changes
It's a 👍🏾 from me!

### :heavy_check_mark: Approved!

Good luck with your next projects. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2020-01-31 15:33 UTC, merged